apiVersion: v1
kind: Service
metadata:
  name: semestre-service
spec:
  type: ClusterIP
  selector:
    app: semestre-service
  ports:
    - port: 8081
      targetPort: 8081
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: semestre-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: semestre-service
  template:
    metadata:
      labels:
        app: semestre-service
    spec:
      containers:
        - name: semestre-service
          image: joseloaiza01/semestre-service:latest
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "1000m"
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres:5432/semestre"
            - name: SPRING_DATASOURCE_USERNAME
              value: "devdb"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "a1b2c3d4"
            - name: JPA_DDL
              value: "create-drop"
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://eureka-server:8761/eureka"
            - name: SERVER_PORT
              value: "8081"
          readinessProbe:
            httpGet:
              path: /health
              port: 8081
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 8081
            initialDelaySeconds: 30
            periodSeconds: 20
            failureThreshold: 5

